### ISSUE TITLE
Fix indentation/spacing/code formatting

### ISSUE THREAD

**Issue by kostasx** [ssoc1KAdamidis/projectTeam#10]
https://github.com/ssoc1KAdamidis/projectTeam/blob/7eb158036e1d29da8a36dbab57635e701f414a7d/src/views/Courses.jsx#L23

The indentation on this page (and all other pages of course) must reflect the nesting level of each element.

Also, try to be consistent with code formatting and spacing. For example:

```js
      online={online}
      dates = {dates}  
```

`online` has no spaces before/after the `=` and the curly braces, whereas `dates` has spaces. Pick one syntax and stick with it.

**Comment by ntinab** [comment]
✓
