### ISSUE TITLE
Refactor, so that the online property gets assigned a proper value 

### ISSUE THREAD

**Issue by kostasx** [ssoc1KAdamidis/projectTeam#12]
https://github.com/ssoc1KAdamidis/projectTeam/blob/7eb158036e1d29da8a36dbab57635e701f414a7d/src/views/EditCourse.jsx#L40

The `online` property is **not** getting assigned the value that you probably think is assigned to it:

`online: setIsChecked(data.online)`
=>
`online: undefined`

The value assigned to `online`, is the value returned by the call to the `setIsChecked()` function, which is always undefined.

**Comment by kostasx** [comment]
@ntinab @giorgostza @ssoc1KAdamidis @ssoc1smargaritis Συγχαρητήρια παιδιά για τη δουλειά στο Project! 💯 

Δείτε ένα ένα τα σχόλια που έχω αφήσει και εάν έχετε ερωτήσεις, μου λέτε.

**Comment by ntinab** [comment]
Δεν ξέρουμε πως να το διορθώσουμε αυτό.

Θέλουμε το online να κρατάει το value που είχε το μάθημα πριν και να εμφανίζεται το checkbox στην edit form είτε checked είτε όχι - αντίστοιχα με το τι ήταν.

**Comment by kostasx** [comment]
Εδώ θα πρέπει να αποφασίσετε να περάσετε μια τιμή (και όχι undefined που παίρνει τώρα).

Θα πρέπει να επιλέξετε ανάμεσα στις `data.online` και `isChecked`:


Π.χ.

`online: isChecked` ή `online: data.online`

Δοκιμάστε, και ανάλογα με την συμπεριφορά, επιλέξτε αυτό που σας δίνει τη τιμή που επιθυμείτε.
