### ISSUE TITLE
alt img attribute values should be in 'Sentence Case' not 'snake_case' format

### ISSUE THREAD

**Issue by kostasx** [ssoc1KAdamidis/projectTeam#13]
https://github.com/ssoc1KAdamidis/projectTeam/blob/f5806d33b2be0d90628180b04a57faab4d34c7fe/src/views/CoursePage.jsx#L70

alt="edit_course" -> alt="Edit course"

[Sentence case](https://www.k-state.edu/grad/academics/etdr/write/sentence-case.html#:~:text=The%20title%20of%20your%20thesis,would%20when%20writing%20a%20sentence.)

**Comment by kostasx** [comment]
Αυτό το PR έχει κλείσει, αλλά βλέπω ότι ο κώδικας δεν έχει αλλάξει: https://github.com/ssoc1KAdamidis/projectTeam/blob/f5806d33b2be0d90628180b04a57faab4d34c7fe/src/views/CoursePage.jsx#L70

**Comment by ntinab** [comment]
Το έκλεισα εγώ ναι, γιατί το διόρθωσα, αλλά δεν έχω κάνει ακόμη push γιατί φτιάχνω τα br.

**Comment by kostasx** [comment]
Τέλεια! Ευχαριστώ για την άμεση ανταπόκριση. 
Σε πραγματικές συνθήκες (σε μια ομάδα, εταιρία, π.χ.) θα πρέπει να κλείνουμε το PR μόνο μετά το commit+push. :)

**Comment by ntinab** [comment]
Δεν το ήξερα, συγγνώμη!
