### ISSUE TITLE
Avoid using `br` tags for spacing and styling

### ISSUE THREAD

**Issue by kostasx** [ssoc1KAdamidis/projectTeam#3]
https://github.com/ssoc1KAdamidis/projectTeam/blob/7eb158036e1d29da8a36dbab57635e701f414a7d/src/views/Dashboard.jsx#L18

Avoid using `<br>` tags for spacing/styling. Use CSS instead.

**Comment by ntinab** [comment]
Εδώ αναφέρεστε σε όλα τα tags ή στο συγκεκριμένο?

Αν αναφέρεστε σε όλα τα tags, ο μοναδικός τρόπος για να εμφανιστούν οι σελίδες μας όπως θέλουμε είναι να τοποθετήσουμε τα πάντα σε div και να ρυθμίσουμε από το css το margin τους? ΄Η υπάρχει κάποιος πιο έυκολος τρόπος για να μην έχουμε br tags και να εμφανίζονται οι σελίδες όπως θέλουμε?

**Comment by kostasx** [comment]
9 στις 10 φορές, η χρήση του br γίνεται (λανθασμένα) διότι υπάρχει η ανάγκη να προσθέσουμε κενό μεταξύ 2 περιοχών στο HTML.

Όπως αναφέρει το MDN:

"Note: Do not use `<br>` to create margins between paragraphs; wrap them in [<p>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) elements and use the [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [margin](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) property to control their size."

Στην συγκεκριμένη περίπτωση, φαίνεται ότι η χρήση του γίνεται για να προστεθεί κάποιο κενό (κάθετα) ανάμεσα στις δυο περιοχές (StatsList και CourseTable). Σε αυτή την περίπτωση θα πρέπει, όπως αναφέρεις σωστά @ntinab να χρησιμοποιηθεί CSS margin στο div .

Επίσης, μήπως θα μπορούσαν αυτά τα 2 'σκόρπια' div να μεταφερθούν μέσα στα Component που τα χρειάζονται; Δηλαδή τα StatsList και CourseTable, και να καθαρίσει κάπως το markup του Dashboard;

**Comment by ntinab** [comment]
Έχουμε αφήσει 16 br tags μόνο στις 2 φόρμες στο Dates και στο Price, γιατί είναι ίδιo input και δεν καταφέραμε να τα κάνουμε access μέσω css.

**Comment by kostasx** [comment]
Σύμφωνα με το [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#technical_summary) το permitted content των `label` elements δεν πρέπει να περιέχει άλλα label elements:

"Permitted content: Phrasing content, but **no descendant label** elements."

- Οπότε, για τα sections των Price και Dates θα πρέπει να αφαιρέσετε τα parent labels. Τα Price και Dates text θα εμφανίζονται κανονικά, μιας και το form έχει `display flex` με `flex-direction: column`.
- Αντί των `<br/>`, θα βάλετε τα ζευγάρια `label + input` μέσα σε `<div>` για να μπουν σε μια καινούργια γραμμή, π.χ.

```
<div>
  <label htmlFor="start_date">Start Date:</label>
  <input ... />
<div>
<div>
  <label htmlFor="end_date">End Date:</label>
  <input ... />
<div>
```
- Μην ξεχνάτε ότι τα htmlFor πηγαίνουν ζευγάρι με τα id (και όχι τα name attributes), οπότε θα πρέπει κάθε label να συνοδεύεται από ένα input με αντίστοιχο id name (π.χ. τα start_date, end_date δεν έχουν id)

@ntinab
